name: gbpusd

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - env:
          OANDA_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          OANDA_API_TOKEN:  ${{ secrets.API_TOKEN }}
          OANDA_ENV:        live
        run: python gbpusd_bot.py
